#      _   _           _     _____  _             _                    #
#     | \ | |         | |   |  __ \| |           (_)                   #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___          #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|         #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \         #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/         #
#                                           __/ |                      #
#                                          |___/                       #
#                          Servidor de Suporte                         #
#                         discord.gg/JtTN7E6A2q                        #

server:
  # Servidor em que o plugin está
  # Caso o modo seja RECEIVE, servirá de referência para o outro plugin que está agindo como SEND.
  current: "mina"
  # Servidor que receberá os dados
  target: "rankup"


